version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
  sqlsc.web:
    image: ${DOCKER_REGISTRY-}sqlscweb
    build:
      context: .
      dockerfile: SQLSC.Web/Dockerfile
