# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - efweb-sql-sc-ne

on:
  push:
    branches:
    - 'main'
    paths:
      - 'WebWithEFC6/**'
  pull_request:
    paths:
    - 'WebWithEFC6/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build WebWithEFC6/WebWithEFC6.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish WebWithEFC6/WebWithEFC6.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: dotnet restore tools
        run: |
            cd WebWithEFC6 
            dotnet tool restore
            dotnet ef migrations bundle --self-contained --force -r linux-x64

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload Ef migrations artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: efmigration
          path: ${{github.workspace}}/WebWithEFC6/efbundle

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: Download  efmigration artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: efmigration

      - name: "Run efmigrations"
        run: efbundle --help

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'efweb-sql-sc-ne'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AFFC8D14FB144F77A67F4835439D4829 }}
          package: .
